spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: gateway-service
logging:
  config: classpath:logback-spring.xml
management:
  endpoints:
    web:
      exposure:
        include: health,info
