server:
  port: 8080
spring:
  data:
    redis:
      host:
      port:
      password:
      database: 0
  cloud:
    nacos:
      discovery:
        server-addr:
        namespace: prod
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/roles/**,/api/permissions/**,/oauth2/**
        - id: stream-service
          uri: lb://stream-service
          predicates:
            - Path=/api/chat/**
          metadata:
            response-timeout: -1
            connect-timeout: 5000
        - id: biz-service
          uri: lb://biz-service
          predicates:
            - Path=/api/sessions/**,/api/messages/**
      httpclient:
        response-timeout: 30s
        connect-timeout: 5000
