spring:
  profiles:
    active: @spring.profiles.active@
  application:
    name: user-service
logging:
  config: classpath:logback-spring.xml
  file:
    path: logs
management:
  endpoints:
    web:
      exposure:
        include: health,info
