server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr:
        namespace: prod
rocketmq:
  name-server:
  producer:
    group: stream-service-producer
    send-message-timeout: 3000
python:
  engine:
    base-url:
    max-connections: 500
    acquire-timeout: 3000
    connect-timeout: 5000
    response-timeout: 310000
stream:
  sse:
    heartbeat-interval: 15s
    max-duration: 300s
internal:
  token:
